on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fys-help-bot:$(date +%s)
      # push to githubs docker registry
      - name: Log in to the GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push the Docker image to Docker Hub
        run: docker push fys-help-bot:$(date +%s)
